#!/bin/sh

# default values
gem5_dir="/home/cs1952y-user/gem5"
isa="RISCV"
build_type="debug"

usage() {
  echo "Usage: $0 [-i <ISA>] [-b <build type>] [--help]"
  echo "  -i      Set ISA (default: $isa)"
  echo "  -b      Set build type (default: $build_type)"
  echo "  --help  Display this help message and exit"
  exit 1
}

# check for --help flag
for arg in "$@"; do
  if [ "$arg" = "--help" ]; then
    usage
  fi
done

# parse command-line arguments
while getopts ":i:b:" option; do
  case $option in
    i) 
      isa="$OPTARG"
      ;;
    b) 
      build_type="$OPTARG"
      ;;
    \?) 
      echo "Invalid option -$OPTARG" >&2
      usage
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      usage
      ;;
  esac
done

# change to gem5_dir before compiling
cd "$gem5_dir" || { echo "Failed to change to directory $gem5_dir"; exit 1; }

# compile gem5
compile_command="python3 $(which scons) build/$isa/gem5.$build_type -j 4"

echo "Compiling gem5..."
yes | $compile_command

echo "Compilation completed."
